#!/usr/bin/env python3
"""
Quick Barrier Enhanced Config Generator
Generates a minimal barrier.conf for quick setup
"""

import os
import sys

def get_local_info():
    """Get local network info"""
    hostname = os.uname().nodename.split('.')[0]

    # Try to get IP address
    ip = "192.168.1.100"  # Default
    try:
        import socket
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
    except:
        pass

    return hostname, ip

def generate_server_config(hostname, ip, clients):
    """Generate server config"""
    width = input("Screen width [1920]: ").strip() or "1920"
    height = input("Screen height [1080]: ").strip() or "1080"

    config = f"""# Barrier Enhanced - Server Configuration
# Generated by quick-setup.py

section: screens
    {hostname}:
        {ip}:0,{width},{height},0,0

"""
    for client in clients:
        config += f"""    {client}:
        1.2.3.4:0,0,0
"""

    config += """
        # Performance options
        localShortcutMode = true
        lowLatencyMode = true
        clipboardSharing = true

end

section: aliases
"""
    for client in clients:
        config += f"""    {client}:
        {client}
"""

    config += "end\n"
    return config

def generate_client_config(hostname, server_ip):
    """Generate client config"""
    config = f"""# Barrier Enhanced - Client Configuration
# Generated by quick-setup.py

section: screens
    {hostname}:
        {server_ip}:24800

        # Performance options
        lowLatencyMode = true
        clipboardSharing = true

end
"""
    return config

def main():
    print("=" * 50)
    print("  Barrier Enhanced - Quick Setup")
    print("=" * 50)
    print()

    hostname, ip = get_local_info()
    print(f"Detected hostname: {hostname}")
    print(f"Detected IP: {ip}")
    print()

    role = input("Is this [s]erver or [c]lient? [s/c]: ").strip().lower()

    if role == 's':
        clients_input = input("Client hostnames (comma separated): ").strip()
        clients = [c.strip() for c in clients_input.split(',') if c.strip()]

        config = generate_server_config(hostname, ip, clients)
        filename = "/tmp/barrier-server.conf"

    elif role == 'c':
        server_ip = input("Server IP address: ").strip()
        config = generate_client_config(hostname, server_ip)
        filename = "/tmp/barrier-client.conf"

    else:
        print("Invalid option!")
        sys.exit(1)

    # Save config
    with open(filename, 'w') as f:
        f.write(config)

    print()
    print(f"Configuration saved to: {filename}")
    print()
    print("To use:")
    print(f"  Server: barrierg -c {filename}")
    print(f"  Client: barrierc -c {filename}")
    print()
    print("Or copy to ~/.config/barrier/barrier.conf for auto-start")

if __name__ == "__main__":
    main()
